name: "Build and Release"
description: "Build and release the .NET 7 WPF application as a single file with trimmed dependencies"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore
      shell: pwsh

    - name: Build
      run: dotnet build --configuration Release --no-restore
      shell: pwsh

      # TODO: Fix this step
#    - name: Publish as Single File
#      run: |
#        dotnet publish --configuration Release --no-restore --runtime win-x64 --output ./publish /p:PublishSingleFile=true /p:PublishReadyToRun=true
#      shell: pwsh

    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output ./publish
      shell: pwsh

    - name: Archive Artifacts
      run: Compress-Archive -Path ./publish/* -DestinationPath ./publish/WowConfigCopy.zip
      shell: pwsh
