name: Manual Build, Release, and Upload

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag for the release'
        required: true
        default: 'WowConfigCopy'

permissions:
  contents: write
  packages: write

jobs:
  build-release-upload:
    environment: Release
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Release WowConfigCopy
        uses: ./.github/templates/BuildAndRelease

      - name: Create and Publish a Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tagName }}
          files: ./publish/WowConfigCopy.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
